// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var BodyParser = require("body-parser");

function json() {
  return BodyParser.json();
}

exports.json = json;
/* body-parser Not a pure module */
