// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Cors = require("cors");
var Express = require("express");

function init($staropt$star, _) {
  var useCors = $staropt$star ? $staropt$star[0] : true;
  var app = Express();
  if (useCors) {
    app.use(Cors());
  }
  return app;
}

function get(prim, prim$1, prim$2) {
  prim.get(prim$1, prim$2);
  return /* () */0;
}

function post(prim, prim$1, prim$2) {
  prim.post(prim$1, prim$2);
  return /* () */0;
}

function put(prim, prim$1, prim$2) {
  prim.put(prim$1, prim$2);
  return /* () */0;
}

exports.init = init;
exports.get = get;
exports.post = post;
exports.put = put;
/* cors Not a pure module */
