// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Cors = require("cors");
var Express = require("express");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function init($staropt$star, _) {
  var useCors = $staropt$star !== undefined ? $staropt$star : true;
  var app = Express();
  if (useCors) {
    app.use(Cors());
  }
  return app;
}

function pipe(i, o) {
  i.pipe(o);
  return o;
}

function writeHead(resp, headers, code) {
  resp.writeHead(code, Js_null_undefined.fromOption(headers));
  return /* () */0;
}

function Request_000(prim) {
  return prim.body;
}

function Request_001(prim) {
  return prim.headers;
}

function Request_002(prim) {
  return prim.params;
}

function Request_003(prim) {
  return prim.path;
}

function Request_004(prim) {
  return prim.query;
}

function Request_005(prim) {
  return prim.originalUrl;
}

var Request = [
  Request_000,
  Request_001,
  Request_002,
  Request_003,
  Request_004,
  Request_005
];

function Response_000(prim) {
  prim.end();
  return /* () */0;
}

function Response_001(prim, prim$1) {
  return prim.get(prim$1);
}

function Response_002(prim, prim$1) {
  return prim.json(prim$1);
}

function Response_003(prim, prim$1) {
  return prim.location(prim$1);
}

function Response_005(prim, prim$1) {
  return prim.send(prim$1);
}

function Response_006(prim, prim$1, prim$2) {
  return prim.set(prim$1, prim$2);
}

function Response_007(prim, prim$1) {
  return prim.set(prim$1);
}

function Response_008(prim) {
  return prim.headersSent;
}

function Response_009(prim, prim$1) {
  return prim.status(prim$1);
}

var Response = [
  Response_000,
  Response_001,
  Response_002,
  Response_003,
  pipe,
  Response_005,
  Response_006,
  Response_007,
  Response_008,
  Response_009,
  writeHead
];

function listen(prim, prim$1) {
  prim.listen(prim$1);
  return /* () */0;
}

function use(prim, prim$1) {
  prim.use(prim$1);
  return /* () */0;
}

function get(prim, prim$1, prim$2) {
  prim.get(prim$1, prim$2);
  return /* () */0;
}

function post(prim, prim$1, prim$2) {
  prim.post(prim$1, prim$2);
  return /* () */0;
}

function put(prim, prim$1, prim$2) {
  prim.put(prim$1, prim$2);
  return /* () */0;
}

function Router_000(prim, prim$1, prim$2) {
  prim.get(prim$1, prim$2);
  return /* () */0;
}

function Router_001(prim, prim$1, prim$2) {
  prim.post(prim$1, prim$2);
  return /* () */0;
}

function Router_002(prim, prim$1, prim$2) {
  prim.put(prim$1, prim$2);
  return /* () */0;
}

function Router_003(prim) {
  return prim.Router();
}

var Router = [
  Router_000,
  Router_001,
  Router_002,
  Router_003
];

exports.Request = Request;
exports.Response = Response;
exports.init = init;
exports.listen = listen;
exports.use = use;
exports.get = get;
exports.post = post;
exports.put = put;
exports.Router = Router;
/* cors Not a pure module */
